---
  # This widget displays recent publications from `content/publication/`.
  widget: "publications"
  active: true
  date: 2016-04-20
  
  title: "Publications"
  subtitle: ""
  
  # Order that this section will appear in.
  weight: 20
  
  # Number of publications to list.
  count: 10
  
  # List format.
  #   0 = Simple
  #   1 = Detailed
  #   2 = APA
  #   3 = MLA
  list_format: 3
  
  # Filter by publication type.
  # -1: Any
  #  0: Uncategorized
  #  1: Conference proceedings
  #  2: Journal
  #  3: Work in progress
  #  4: Technical report
  #  5: Book
  #  6: Book chapter
  publication_type: "-1"
  
  # Exclude publications that are shown in the Selected Publications widget?
  exclude_selected: false
---


```{r DT, echo=FALSE}
library(RefManageR)
library(data.table)

# TODO link pdf
# todo equal contrib annotation
# get citations

refs <- RefManageR::ReadZotero(group = "14341", .params = list())
dt <- as.data.table(refs)[,.(Year = year, 
                             Title = title, 
                             doi, 
                             Journal = journal,
                             Authors = author)]
dt[, Title := gsub("\\{|\\}", "", Title)]
dt[, Authors := gsub(" and ", ", ", Authors)]
dt[, Authors := gsub("Q. Geissmann", "**Q. Geissmann**", Authors)]
dt[, Title := sprintf('[%s](http://dx.doi.org/%s)',Title, doi)]
# dt[, Authors := gsub("Q. Geissmann", "<b>Q. Geissmann</b>", Authors)]
# dt[, Title := sprintf('<a href="http://dx.doi.org/%s">%s</a>',doi, Title)]
# refs_gs <- RefManageR::ReadGS("sgSsPvUAAAAJ")
dt[, doi:=NULL ]
setkeyv(dt, "Year")
dt <- dt[.N:1]

```


```{r}
library(knitr)
library(kableExtra)

knitr::kable(dt, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r, echo=FALSE, eval=FALSE}
library(DT)
author_js <- JS(
  "function(data, type, row, meta) {",
  'lst = data.split(",");',
  "if(lst.length >3){",
     'display = [lst[0],lst[1],"…,",lst.slice(-1)[0]].join(", ");',
  "}",
  "else{",
      "display=data;",
  "}",
  
  'display = display.split(",");',
  'data = data.split(",");',
  "if(display.length > 1){",
     'display = display.slice(0,-1).join(", ") + " and" + display.slice(-1);',
     'data = data.slice(0,-1).join(", ") + " and" + data.slice(-1);',
  "}",
  "else{",
     "display=data;",
  "}",
  "return '<span title=\"' + data + '\">' + display + '</span>';",
  "}"
)

options = list(columnDefs = list(list(
                      targets = which(colnames(dt) == "Authors") - 1,
                      render = author_js
                    )))
out <- datatable(dt, 
                  options = options,
                  rownames = FALSE,
                  escape = FALSE,
                 #filter = "bottom"
                 
                  )
```